language: android

branches:
  only:
    - dev
    - master

script: "./gradlew build"

android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.0.0

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
