language: android
branches:
  only:
  - dev
  - travis_test
  - master
script: "./gradlew check assembleDebug"
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.0
  - android-22
  - extra-google-m2repository
  - extra-android-m2repository
env:
  global:
  - secure: fwPqjObm6WRRY7Dg+vQGznlC7hMlvStgdOlWloRB2M5RPUBwbc2akKeKP1lITMPlMDEXHhx6m5OTQwjDel8Z/7ej5XkjsoxXOlKH+S//aD05lzza50eGDSWNVGSR40Qau8aG0coO51cnkE4RwplhKo0aBhX1a2/AlirlpBeHnK8=
  - secure: vJTr0HekfIMFu1UUSY0KERyz23KsRzeDlIJebaTYro8maRqG4CE4ek/T1+fktqazJpBI9yYGN9UbwQK8evyfhQ9k873rBlJ/3vzPADqQGicq5ivhUrreNljdFEaxp8lmvVQ/2n23/KjTFvcrWrlbIS2NZ+5Wfsn5ZKU4npVdlXA=
  - secure: ss/TsDJ7f0ZrxpwunUOymU8bojBy35qluCX4rpylOfWIHo3n5psNP3aNL86dl/YSeuPjBNwPnKeOKxW0SBhwSIbfFMQV6/K4fssE5EeAF8OURrS0/kZ9PAmHgCXSbY2O95iQsj2oFJsIge5R10utCTsYNAZ5ySJWk7bN8uiyU/E=
  - secure: LjbFrScNzX0QKBl4nkiCjmJUcCrjh/fnzPucOAhf69vD/mTCS5pmuyG/dP4b29BO/Y0S2mZ6zMk1cs8WHPr3XxaXLUCaXHXWB5RyXSAuPGBrMHu8KRyCu1tUmO9bRsVIPNmQziIw8WjsMDB0cEEhmYaXZpXhDi9QoCUgCT5PSlI=
